### ISSUE TITLE
需要一些帮助 / nedd some help

### ISSUE THREAD

**Issue by Aneeqasif** [maoiscat/mpv-dark-box#1]
hello sir i want to change look of this osd a lil bit ,  i actually want to decrease the width of this control panel (osd) how can i do that , i mean which line of (.lua file) i have to change to decrease the width. thanks in advance
___
您好先生，我想更改此osd的外观，实际上我想减小此控制面板（osd）的宽度，我该怎么做，我的意思是我必须更改（.lua文件）的哪一行以减少宽度。提前致谢

**Comment by maoiscat** [comment]
1159:        w = 800,    -- width
